[project]
name = "hass-tarif-edf"
version = "1.1.3"
description = "Home Assistant integration to retrieve EDF electricity tariffs (Base, HP/HC, Tempo)"
requires-python = ">=3.14.2"

[dependency-groups]
dev = [
    "pytest-homeassistant-custom-component==0.13.365",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
testpaths = ["tests"]
